#注册到的服务地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka,http://localhost:8083/eureka
  #配置点击跳转地址
  instance:
    hostname: eureka.client
spring:
  application:
    name: eureka-cient
server:
  port: 8081
