spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/VitasYuan/microservice-config.git
          username:
          password:
          basedir: /Users/yuanweipeng/Documents/workspaces/study-notes/study-notes/config
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka

server:
  port: 8088

management:
  endpoints:
    web:
      exposure:
        include: "*"
